const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.Browser,
		C3.Plugins.TextBox,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Button.Acts.SetText,
		C3.Plugins.System.Exps.chooseindex,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Button.Cnds.CompareText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.find,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Exps.left,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.trim,
		C3.Plugins.TextBox.Acts.AppendText,
		C3.Plugins.System.Exps.uppercase
	];
};
self.C3_JsPropNameTable = [
	{f: 0},
	{c: 0},
	{b_letra: 0},
	{Letra: 0},
	{FondoEnMosaico: 0},
	{FondoEnMosaico2: 0},
	{n: 0},
	{P: 0},
	{P1: 0},
	{Mouse: 0},
	{Rellenar: 0},
	{Sin_color: 0},
	{Orientacion: 0},
	{Navegador: 0},
	{screenshot: 0},
	{EntradaDeTexto: 0},
	{CARGAR: 0},
	{Palabras: 0},
	{Letras: 0},
	{Fila: 0},
	{Columna: 0},
	{Longitud: 0},
	{Palabra: 0},
	{Palabra_Ivertida: 0},
	{Caracter: 0},
	{i: 0},
	{color: 0},
	{ban: 0},
	{i_boton: 0},
	{i_palabra: 0},
	{c_gusano: 0},
	{f_gusano: 0},
	{contador: 0},
	{a: 0},
	{b: 0}
];

self.InstanceType = {
	Letra: class extends self.ITextInstance {},
	FondoEnMosaico: class extends self.ITiledBackgroundInstance {},
	FondoEnMosaico2: class extends self.ITiledBackgroundInstance {},
	P1: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Rellenar: class extends self.IButtonInstance {},
	Sin_color: class extends self.IButtonInstance {},
	Orientacion: class extends self.IButtonInstance {},
	Navegador: class extends self.IInstance {},
	screenshot: class extends self.IButtonInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	CARGAR: class extends self.IButtonInstance {},
	Palabras: class extends self.ITextInstance {},
	Letras: class extends self.ITextInstance {}
}